apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: server
          image: lakshaybabbar/server:04
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-secret
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-secret
                  key: MONGO_PORT

---
kind: Service
apiVersion: v1
metadata:
  name: web-app-svc
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: web-app
  type: LoadBalancer
